feat: Add recompute flag to shellenv command
jetify-com/devbox pull request #1963
Opened 2024-04-05 13:59 UTC by dax

## Summary

(related [issue](https://github.com/jetpack-io/devbox/issues/1882))
When used with direnv and when regularly switching between branches, Devbox slows down the workflow because it tries to keep the packages in sync with the devbox.lock state with a Ensuring packages are installed.
This PR add the `--recompute` flag to the `shellenv` command that allow to set it to `--recompute=false` and then disable the automatic installation of package in case `devbox.json` is out of sync.

## How was it tested?

Setting the `.envrc` (ie. the direnv config file) as:
```
devbox shellenv --init-hook --no-refresh-alias --recompute=false
```

`--install` has been removed and `--recompute=false` compared with what `devbox generate direnv --print-envrc` generate by default.

Then updating `devbox.json` does not trigger package installation or removal but the context (ie. the env vars) are correctly updated.

2024-04-08 17:31 UTC, savil reviewed
Thanks! I generally like the approach. That said, looking at the implementation I think a nicer fix would be to push the flag inside `shellEnvCmd` function's implementation.

Right now, we have this awkward parameter in `func shellEnvCmd(recomputeEnvIfNeeded *bool)` because we wanted it selectively exposed for just global and not regular devbox. If we're seeking to expose the `--recompute` flag in both global and regular devbox, then no need to expose this parameter. The flag can be handled internally inside `shellEnvCmd`.

Would you wanna make that change? If you are strapped for time, then happy to approve this PR, land it and I can make a follow up fix for it.

2024-04-08 17:33 UTC, savil commented
would you mind also running `devbox run lint` to ensure the code is considered "clean"?

2024-04-08 17:33 UTC, savil commented
`devbox run fmt` should help with formatting concerns

2024-04-09 06:18 UTC, dax commented
> Would you wanna make that change?

Thank you @savil for the suggestion. I'll push an update soon (and run the linter and formatter 😄 )

2024-04-09 11:15 UTC, dax commented
@savil The PR is now ready 🙏

2024-04-11 17:59 UTC, mikeland73 requested changes
I think adding this flags makes sense, but the current implementation will cause a change in behavior in global shellenv (because recompute was previously defaulted to false, and now it is defaulted to true).

I think you may be able to simply override the flag in the global case (but we need some testing to confirm, cobra internals don't always behave intuitively).

2024-04-23 09:51 UTC, dax commented
Thanks @mikeland73 for spotting the regression 🙏 
I guess I can close this PR as @savil now have submitted a cleaner one 🙏

2024-04-23 09:51 UTC, closed without merging