[docker] Added fix to run image release on tags creation + backfill action
jetify-com/devbox pull request #2118
Opened 2024-06-03 19:33 UTC by mohsenari

## Summary
TSIA

## How was it tested?
Will have to be tested via github actions run on a tag creation. But backfill will be tested manually

2024-06-04 18:05 UTC, mikeland73 requested changes
I'm a bit confused by this action. It doesn't seem like the version is added to the image at all? Is this just meant to refresh the latest image? (`DEVBOX_USE_VERSION` is not set, so it looks like no matter what the docker image will use the latest version)

Also, are the actions identical? You should just add `workflow_dispatch` to existing one and can have `ref` defaulted correctly.

2024-06-04 21:20 UTC, mohsenari commented
> I'm a bit confused by this action. It doesn't seem like the version is added to the image at all? Is this just meant to refresh the latest image? (`DEVBOX_USE_VERSION` is not set, so it looks like no matter what the docker image will use the latest version)

The repo checkout action checks out the code at the provided tag. But good point on not having `DEVBOX_USE_VERSION` I added that to the build args for dockerfile and the action and tested locally to make sure it build the provided version.

> 
> Also, are the actions identical? You should just add `workflow_dispatch` to existing one and can have `ref` defaulted correctly.

The actions are similar but not identical. Frankly, I don't know how I can branch the logic in a YAML file to do the current tag and update latest if inputs aren't provided. This action can be deleted once we successfully backfill the older devbox versions in dockerhub

2024-06-05 00:36 UTC, mikeland73 reviewed
What I had in mind was something like https://github.com/jetify-com/devbox/commit/854361958d374a155f01dd8decd9ac3353f2f7fc

I'm still a bit confused about what we're doing with versions. Currently, every time a tag is pushed we publish a latest without a version. I guess this is fine (it basically helps update the launcher, etc)

This does mean we don't really need to "backfill" anything. We've never actually published individual tags. I think just adding `workflow_dispatch` to the existing job is probably enough.

For future thought:
Ideally we publish latest only for newest tag (there's a latest=auto on the docker meta action, but I'm not sure how it works). In addition we also publish each individual tag with the env variable. Ideally we also pre-install the binary on the docker image so it doesn't need to be installed after the container is initialized.

2024-06-05 19:56 UTC, mikeland73 approved these changes

2024-06-05 20:04 UTC, merged